name: Deploy to Vercel Production

on:
  push:
    branches:
      - master
    paths:
      - 'service/**/*'

  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './service'
          
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Install dependencies
        working-directory: ./service
        run: npm ci
      - name: Build
        working-directory: ./service
        run: npm run build
      - name: Saving build
        uses: actions/upload-artifact@v4
        with:
          name: vercel-output
          path: ./service/.vercel
          if-no-files-found: error
          include-hidden-files: true
          retention-days: 1
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: vercel-output
          path: ./service/.vercel
      - name: Deploy to Vercel
        run: vercel deploy --cwd ./service --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
    
